[project]
name = "b12"
version = "0.1.0"
description = ""
authors = [
    {name = "Vadim",email = "headcra6@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
]

[tool.poetry.group.dev.dependencies]
black = ">=26.1.0,<27.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
